### ISSUE TITLE
Ready for v0.3.0?

### ISSUE THREAD

**Issue by Kijewski** [rinja-rs/rinja#101]
We have added and changed [a lot](https://github.com/rinja-rs/rinja/compare/v0.2.0...d39ee220fd23633f8bf401cbf76d88d3d76f58bf) since the first release. Do you think we are ready for 0.2.1? I think rinja_parser has to get bumped to 0.3.0, because we added removed enum members, but the current HEAD should be compatible to rinja + rinja_derive 0.2.0.

What do you think, @GuillaumeGomez? Do you have something you wish to add or change before we do the next release?

**Comment by GuillaumeGomez** [comment]
Actually yes! I wanted to add [slice pattern matching](https://github.com/djc/askama/issues/342) before a new release. But that's the only thing I can think of on my side.

**Comment by Kijewski** [comment]
Yes, that can be quite a useful feature, too! I guess the parsing is 99% the same as parsing tuples, except for the delimiters.

**Comment by Kijewski** [comment]
Or do you want to implement `if let [b'H', b'i', b' ', who @ .., b'!'] = b"Hi world!"`, too? I guess that could be difficult. <https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ea373fd285476e52d131a83724293372>

**Comment by GuillaumeGomez** [comment]
I suppose the whole `@ ..` should be implemented. Gonna be fun. :3

**Comment by GuillaumeGomez** [comment]
Should we make the release now (I'll let you make this one :stuck_out_tongue:)? Gonna work on the `b`/`c` prefixes later on. Gonna open an issue for that.

**Comment by Kijewski** [comment]
Will do a release later this evening (CEST).  :)

**Comment by GuillaumeGomez** [comment]
Yeay! \o/

**Comment by Kijewski** [comment]
Released: https://github.com/rinja-rs/rinja/releases/tag/v0.3.0 :)

**Comment by GuillaumeGomez** [comment]
Wow looks nice! I wonder if we could automate that too. XD

Anyway, thanks a lot, it's awesome! Announcing on socials.

**Comment by Kijewski** [comment]
When you click on [Releases](https://github.com/rinja-rs/rinja/releases), then on the top-right there is a button "draft new release". There you can select the newest tag, and with "Generate release notes" you get the same output as in my release message. :)

Unless I forget it, I check the "Create a discussion for this release" box, so the easier to answer questions or any comments to the release can get consolidated into one page

**Comment by GuillaumeGomez** [comment]
Oh nice, thanks for the information! We should put it in a "releasing.md" file to have the list of things we need to do when releasing.
