### ISSUE TITLE
Filters `|fmt` and `|format` needlessly (?) allocate string

### ISSUE THREAD

**Issue by Kijewski** [rinja-rs/rinja#113]
The filters `|fmt` and `|format` use [`format!()`](https://doc.rust-lang.org/stable/std/macro.format.html), but I think they could use [`format_args!()`](https://doc.rust-lang.org/stable/core/macro.format_args.html), so they don't have to allocate a string to do their work. Are there any drawbacks to replacing their `format!()` call with `format_args!()`?

**Comment by GuillaumeGomez** [comment]
Good idea!

**Comment by Kijewski** [comment]
The lifetimes just wouldn't works. `format_args!` introduces a bunch of ephemeral variables that cannot be moved.
