### ISSUE TITLE
Online code preview 

### ISSUE THREAD

**Issue by Kijewski** [rinja-rs/rinja#114]
What do you think, @GuillaumeGomez, could <https://kijewski.github.io/play-rinja/> / <https://github.com/Kijewski/play-rinja/> be interesting to someone? If it could be (made) interesting, then I'd move it into the organization.

Right now, it's more or less a prove-of-concept.

**Comment by GuillaumeGomez** [comment]
It would be useful to me for sure!

**Comment by Kijewski** [comment]
Moved: https://github.com/rinja-rs/play-rinja + https://rinja-rs.github.io/play-rinja :)

But it seems like I lost my ownership during the transfer, and I also didn't get it back through the org. I hope do can do settings changes and re-invite me. :D

**Comment by GuillaumeGomez** [comment]
Don't you have admin rights to do so normally already?

**Comment by GuillaumeGomez** [comment]
Ah no, you were admin only on this repository. You're now admin of the organization directly.

**Comment by Kijewski** [comment]
Ahh, thank you! :)

**Comment by GuillaumeGomez** [comment]
Well it was a mistake on my end so now it's fixed at least. :)

**Comment by Kijewski** [comment]
<https://rinja-rs.github.io/play-rinja/> is pretty, now. :)

**Comment by GuillaumeGomez** [comment]
It is indeed! Maybe you might want to add a "generate" button to reduce load on your server too.

**Comment by Kijewski** [comment]
All the code generation, highlighting, etc., is all done in the browse in Wasm. No data is transferred. That's why I needed <https://github.com/rinja-rs/rinja/pull/111> and <https://github.com/rinja-rs/rinja/pull/117>. :)

**Comment by GuillaumeGomez** [comment]
Oh wow. That's SUPER cool!

**Comment by GuillaumeGomez** [comment]
Well, just open a PR to add links to your playground then so we can sell even more rinja to the world. :D

**Comment by Kijewski** [comment]
Resolved in #120.
