### ISSUE TITLE
Filters written in Rinja itself

### ISSUE THREAD

**Issue by Kijewski** [rinja-rs/rinja#121]
Do you think something like that could be worthwhile to explore?

```rust
mod filters {
    use super::*;

    #[derive(Template)]
    #[template(path = "show_result.html")]
    struct ShowResult<T: Display, E: Display>(Result<T, E>);
}

#[derive(Template)]
#[template(path = "template_that_uses_the_filter.html")
struct Ttutf {
    result: Result<String, String>,
}
```

#### template_that_uses_the_filter.html
```jinja2
{{ result|ShowResult }}
```

#### show_result.html
```jinja2
{% match self.0 %}
    {% when Ok(val)  %} <i>{{ val }}</i>
    {% when Err(err) %} <b>{{ err }}</b>
{% endmatch %}
```

It's very similar to macros, but a little different. I think it could be handy, because you can do everything in the filter, like extending a base template, that is not possible in macros.

**Comment by GuillaumeGomez** [comment]
How do we know whether `ShowResult` is a function or a type?

**Comment by Kijewski** [comment]
Right now, I think the only problem is that we generate a `?` after the filter invocation. Maybe if we simply omit it if the name starts with a capital letter?

**Comment by GuillaumeGomez** [comment]
I really don't think it's a good idea. I really love the idea to be able to use types like that, but it'd introduce a new "hidden" behaviour, and I did too much python and JS to be able to find it ok. (so much trauma :laughing: )

**Comment by Kijewski** [comment]
Since one can simply write `{{ ShowResult(result) }}` instead of `{{ result|ShowResult }}`, I guess it's not actually needed.
