### ISSUE TITLE
Comparative benchmarks

### ISSUE THREAD

**Issue by Kijewski** [rinja-rs/rinja#134]
I wrote a small, still quite incomplete benchmark suite, because I did not find any public one that is not archived, using the well known "big-table" and "teams" tests: <https://kijewski.github.io/template-benchmark/> + <https://github.com/Kijewski/template-benchmark/>

Gotta say, rinja does quite well! At least in these benchmarks. :)

Do you, @GuillaumeGomez, think that this project should live in this org? At least once the more interesting template engines are added: <https://github.com/flosse/rust-web-framework-comparison?tab=readme-ov-file#templating>?

**Comment by GuillaumeGomez** [comment]
If we use it to benchmark `rinja`, then I think it makes for the projects to be in the org too.

**Comment by Kijewski** [comment]
Moved here: <https://github.com/rinja-rs/template-benchmark>. Now it includes a description and a weekly self-updating table of benchmark results:

[![](https://rinja-rs.github.io/template-benchmark/results.svg)](https://rinja-rs.github.io/template-benchmark/)

**Comment by GuillaumeGomez** [comment]
Nice. :D
