### ISSUE TITLE
parser: `Syntax` is trusted to have valid data

### ISSUE THREAD

**Issue by Kijewski** [rinja-rs/rinja#138]
The fields of `rinja_parser::Syntax` are public and `Ast::from_str()` trusts that the input is valid, e.g. no field contains an empty string.

If a field does contain the an empty string, then in the best case the parser panics. In the worst case it could probably deadlock, in a loop advancing the input by null bytes until you kill the process.

Should the check if the syntax is sane be moved from `rinja_derive::RawSyntax` into `rinja_parser::Syntax`?

**Comment by GuillaumeGomez** [comment]
I think it'd be a good thing to check indeed.
