### ISSUE TITLE
Ready for v0.3.1?

### ISSUE THREAD

**Issue by Kijewski** [rinja-rs/rinja#147]
We've accumulated 105 commits in 93 files with 4,203 additions and 1,585 deletions:  
<https://github.com/rinja-rs/rinja/compare/v0.3.0..e4b5bd944dab490c50c14fe6f1b7836683ac4e54>

Do you think we are ready for our third release? :)

**Comment by GuillaumeGomez** [comment]
I think we are ready for `0.3.1` for sure. :D

**Comment by Kijewski** [comment]
All tests have passed. Should I perform the release or do you want to, to keep alternating (1st you, 2nd I, …)? :D

**Comment by GuillaumeGomez** [comment]
I'm implementing doctests for bin crates currently, so could you do it please? ^^' (Thanks a lot in advance! :smile: )

**Comment by Kijewski** [comment]
Ah, nice! Keep up the good work, then. :D

Released: <https://github.com/rinja-rs/rinja/releases/tag/v0.3.1> :)
