### ISSUE TITLE
Sometimes, a field is not interpreted as such, resulting in invalid code

### ISSUE THREAD

**Issue by GuillaumeGomez** [rinja-rs/rinja#150]
I don't have a minimized case yet, but in docs.rs I have some cases where I neded to put `self.` prefix to ensure it was using the field and not variable which should not exist. You can see `self.name` a few times [here](https://github.com/rust-lang/docs.rs/pull/2591/files#diff-76dcffc0f70c36def219277d7af4d6240e75ef82a9387db79db807df9515b651R133).

**Comment by Kijewski** [comment]
If I see this correctly, then you start using `{{self.name}}` instead of name `{{name}}` from [here](https://github.com/rust-lang/docs.rs/pull/2591/files#diff-76dcffc0f70c36def219277d7af4d6240e75ef82a9387db79db807df9515b651R111) onward. Could the macro call be the reason?

**Comment by GuillaumeGomez** [comment]
That's my current lead. It would mean that we need to put macro calls in their own scope (both in `rinja` generator and in generated rust code).

**Comment by Kijewski** [comment]
On a quick glance, [`write_call()`](https://github.com/rinja-rs/rinja/blob/master/rinja_derive/src/generator.rs#L785) look fine. But it looks like [`write_loop()`](https://github.com/rinja-rs/rinja/blob/master/rinja_derive/src/generator.rs#L702) pushes `self.locals.push()`, but does not pop `self.locals.pop()`. Then [this `for`](https://github.com/rust-lang/docs.rs/pull/2591/files#diff-76dcffc0f70c36def219277d7af4d6240e75ef82a9387db79db807df9515b651R119) could manifest the error. Or the combination of `call` + `for`.

**Comment by GuillaumeGomez** [comment]
Oh nice. That was quick to find out. Still needs a minimal case. ;)

**Comment by Kijewski** [comment]
I did not test my assumption at all. :)

**Comment by Kijewski** [comment]
I wonder if `locals.push()` should return some `#[must_use]` type which is consumed by `locals.pop()`?

**Comment by Kijewski** [comment]
Something like that? (entirely untested)

```impl
struct Scope;

impl Drop {
    #[inline(always)]
    fn drop() {
        extern "C" { fn __should_never_be_called_so_lets_generate_a_linker_error(); }
        unsafe { __should_never_be_called_so_lets_generate_a_linker_error() };
    }
}

impl Locals {
    fn pop(scope: Scope) {
        std::mem::forget(scope);
    }
}
```

**Comment by GuillaumeGomez** [comment]
An even simpler idea: `self.locals.push` expects a closure which will handle the popping.

**Comment by GuillaumeGomez** [comment]
It seems to be a name conflict with the macro somehow. If I rename the `name` argument to something else, it works fine.

**Comment by GuillaumeGomez** [comment]
I have a minimum code! So a loop in a macro is triggering the bug. :)

Here's the code to reproduce it the bug:

```rust
#[derive(Template)]
#[template(
    source = r#"
{%- macro mac(bla) %}
{% for x in &[1] %}
hello {{bla}}
{% endfor %}
{% endmacro -%}

{% call mac(bla=bla) %}
{{bla}}"#,
    ext = "txt"
)]
struct TargetStr {
    bla: u8,
}

fn main() {
    let t = TargetStr { bla: 12 };
    assert_eq!(t.render().unwrap(), "bc hoy");
}
```

Writing a fix now.

**Comment by GuillaumeGomez** [comment]
Just adding the missing `locals.pop()` in `write_loop` fixed the bug, you're really impressive!

**Comment by Kijewski** [comment]
Hehe, thank you! :)

**Comment by Kijewski** [comment]
Should we do a very early 0.3.2 release, now this bug is fixed? I have currently no immediate ideas what else to change for the next release.

**Comment by GuillaumeGomez** [comment]
Very good idea! I can do it tomorrow if you want.

**Comment by Kijewski** [comment]
Yes, that would be nice.

**Comment by GuillaumeGomez** [comment]
Release done! :)
