### ISSUE TITLE
Convert filter tests to use doc tests

### ISSUE THREAD

**Issue by Kijewski** [rinja-rs/rinja#185]
Most built-in filter tests are invoked as normal functions: [builtin.rs#L614-L817](<https://github.com/rinja-rs/rinja/blob/80bb96931b1a325d0ce74af032d62b222c39a233/rinja/src/filters/builtin.rs#L614-L817>). It is good that the functions are tested at all, but it too bad that this kind of test cannot not serve as documentation. Some filters are doc-tested using rinja code blocks [builtin.rs#L53-L72](<https://github.com/rinja-rs/rinja/blob/80bb96931b1a325d0ce74af032d62b222c39a233/rinja/src/filters/builtin.rs#L53-L72>), so the user gets a proper usage example in the documentation. Also, many filters contain some logic in the generator, which has to be tested, too.

It would be nice if some, if not all, filters could be tested with doc tests:

- [x] fmt
- [x] format
- [x] linebreaksbr
- [x] paragraphbreaks
- [x] lower
- [x] lowercase
- [x] upper
- [x] uppercase
- [x] trim
- [x] truncate
- [x] indent
- [x] join
- [x] capitalize
- [x] wordcount
- [x] title
- [x] pluralize
- [x] safe
- [x] escape
- [x] e
- [x] filesizeformat
- [x] json
- [x] urlencode
- [x] urlencode_strict

**Comment by Wollaston** [comment]
I'd be interested in helping out with this one!

Please let me know if you are looking for new contributors and if so, if you would like me to just go through your checklist here top to bottom. My understanding is that you would like doctests added to these filters. Are we adding new tests, or just copying the regular tests to doctests? Thank you!

**Comment by GuillaumeGomez** [comment]
New contributors and contributions are very welcome! From what I can see, in case the filter isn't tested, then you need to create one. If one already exist, I think copying it might be enough.

**Comment by Kijewski** [comment]
Thank you very much, @Wollaston, great work!
