### ISSUE TITLE
Add support for macro argument default value

### ISSUE THREAD

**Issue by GuillaumeGomez** [rinja-rs/rinja#198]
It's possible in [jinja](https://jinja.palletsprojects.com/en/3.1.x/templates/#macros) to have default value for macro arguments:

```jinja
{% macro input(name, value='', type='text', size=20) -%}
    <input type="{{ type }}" name="{{ name }}" value="{{value|e }}" size="{{ size }}">
{%- endmacro %}
```

**Comment by GuillaumeGomez** [comment]
For a first step I think it's enough. We can always add function calls or constructors later on.

Please leave this one to me. :p

**Comment by Kijewski** [comment]
> Please leave this one to me. :p

Hehe, I will. Have fun with it! :D

**Comment by GuillaumeGomez** [comment]
Thanks! :D
