### ISSUE TITLE
Differences from askama?

### ISSUE THREAD

**Issue by tyilo** [rinja-rs/rinja#222]
The README mentions that this is a fork of `askama`, but there seems to be missing some info:
- Why create a fork?
- What are the differences between this and `askama`?

**Comment by tyilo** [comment]
Maybe just adding a paragraph to the README would be enough. You could also link the blog post there.

**Comment by Kijewski** [comment]
@tyilo, good idea! Maybe you would like to open a PR to add the link?

**Comment by tyilo** [comment]
Now `rinja` has been merged into `askama` again?
