### ISSUE TITLE
Using `anyhow::Error` with functions?

### ISSUE THREAD

**Issue by mhammond** [rinja-rs/rinja#224]
The docs re functions etc don't mention anything about errors, but it looks like the `E` in a `Result` must be `Display+Error`. We're using it in a lib using `anyhow::Error`, meaning we need a manual wrapper around everything we want to be callable from rinja, so often just choose to unwrap instead - which seems unfortunate.

Is there something I'm missing, or anything I might be able to do to help with my situation?

**Comment by GuillaumeGomez** [comment]
I'm surprised because [rinja::Result](https://docs.rs/rinja/latest/rinja/type.Result.html) and [askama::Result](https://docs.rs/askama/latest/askama/type.Result.html) seem to have the same traits and trait requirements. Do you have a small example by any chance?

**Comment by mhammond** [comment]
We had the same problem with askama - ie, IIUC, neither askama nor rinja work with `anyhow::Error`.

In my particular example, I was trying to change [this function](https://github.com/mozilla/uniffi-rs/blob/b7b388067534b0295a04a099bfc8b37764af0f9f/uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs#L327) to return `Result<String>` which results in:

```
error[E0599]: the method `rinja_auto_escape` exists for reference `&&AutoEscaper<'_, Result<String, Error>, Text>`, but its trait bounds were not satisfied
   --> uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs:202:10
    |
202 | #[derive(Template)]
    |          ^^^^^^^^ method cannot be called on `&&AutoEscaper<'_, Result<String, Error>, Text>` due to unsatisfied trait bounds
    |
   ::: /Users/skip/.rustup/toolchains/1.77.1-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:502:1
    |
502 | pub enum Result<T, E> {
    | --------------------- doesn't satisfy `_: Display`
    |
    = note: the following trait bounds were not satisfied:
            `std::result::Result<std::string::String, anyhow::Error>: std::fmt::Display`
            which is required by `&&AutoEscaper<'_, std::result::Result<std::string::String, anyhow::Error>, Text>: AutoEscape`
    = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0599`.
```

As a consequence, we have defined our own [error wrapper](https://github.com/mozilla/uniffi-rs/blob/b7b388067534b0295a04a099bfc8b37764af0f9f/uniffi_bindgen/src/backend/filters.rs#L13-L32) which must be used as the `E`, but that means we can't use existing functions from our crate with return `anyhow::Result`.

**Comment by GuillaumeGomez** [comment]
I tried this code and it seems to work fine:

```rust
fn render() -> anyhow::Result<String, rinja::Error> {
    rinja_template.render().into()
}
```

If you want to have something fully compatible with `anyhow`, you'll need to add a convert function:

```
fn convert(err: rinja::Result) -> anyhow::Result<String> {
    err.map_err(|err| err.into())
}

fn render() -> anyhow::Result<String, rinja::Error> {
    convert(rinja_template.render())
}
```

It's not perfect, but seems ok. You can always improve it by creating a trait so you can make it a method but I'm not sure it's worth it. Just having a small function like seems more than enough.

**Comment by mhammond** [comment]
This was a misunderstanding on my part about how all this hangs together. Thanks for your help!
