### ISSUE TITLE
Make `with-axum` feature internal and remove mention from the book?

### ISSUE THREAD

**Issue by tyilo** [rinja-rs/rinja#225]
As you can't just use `rinja::Template` with the `with-axum` feature enabled, but need to use `rinja_axum` instead and `rinja_axum` automatically enables the `with-axum` feature, the feature is basically only needed for internal use.

If you already depend on `rinja_axum`, you will never need to enable the `with-axum` feature, so why expose this feature to the users of the library?

**Comment by GuillaumeGomez** [comment]
Good question. Do we have a use-case for users to mention this feature in the book @Kijewski ?

**Comment by Kijewski** [comment]
No, we don't. Yes, it's bad that we mention the features in the book.

The rest of the description looks wrong, too. E.g. not an empty message in returned for errors, but e.g. an [ErrorResponse](https://docs.rs/axum/latest/axum/response/struct.ErrorResponse.html) which can be caught, styled, etc. by a handler, if I'm not mistaken.
