### ISSUE TITLE
Do we need the `print` argument?

### ISSUE THREAD

**Issue by Kijewski** [rinja-rs/rinja#254]
I don't think I ever wanted to print the AST, and I presume users of rinja certainly didn't, either.

I don't think there is a need to print the generated code anymore, since `cargo expand` and our [playground](https://rinja-rs.github.io/play-rinja/) both do the job better.

Can we remove the feature?

**Comment by GuillaumeGomez** [comment]
I personally use it quite often. ^^'

**Comment by Kijewski** [comment]
Oh, you do? That's at least one more user than I would have expected the feature had. :D Okay, then we'll keep it.

**Comment by GuillaumeGomez** [comment]
I use it mostly on docs.rs when I have compiler error. Instead of expanding all templates, I only print the one I care about.
