### ISSUE TITLE
macros fail on invocation when arguments are rust keywords

### ISSUE THREAD

**Issue by chrisp60** [rinja-rs/rinja#259]
**I am using git main**

I can define this macro without issue

```handlebars
{% macro foo(type="text") %}
    <input type="{{ type }}"/>
{% endmacro foo %}

{# or this one #}

{% macro foo(type) %}
    <input type="{{ type }}"/>
{% endmacro foo %}
```
But calling them produces an error (error shown below).
```handlebars
{% call foo("input") %}
{% call foo(type="input") %}
```

```
error: expected identifier, found keyword `type`
  --> [..path]
   |
30 | #[derive(Template, Debug)]
   |          ^^^^^^^^ expected identifier, found keyword
   |
   = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc-macro derive produced unparsable tokens
  --> [..path]
   |
30 | #[derive(Template, Debug)]
   |          ^^^^^^^^

error[E0609]: no field `r#type` on type `&[Struct with Template derived]`
  --> [..path]
   |
30 | #[derive(Template, Debug)]
   |          ^^^^^^^^ unknown field
   |
   = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)

```

Did not see any issues created in regards to this, or mention in the docs that it should be avoided. Just wanted to point it out in case it does not align with intentions.

As a user, I feel the error should at least come from the definition, and not the invocation. It does seem like the keyword is properly escaped in at least some capacity (the error references `r#type`).

Current workaround, naming the argument something else

**Comment by Kijewski** [comment]
Thank you for the bug report and providing a minimal reproducible example!

Confirmed, there is a `let type = …;` in the generated code, which is obviously invalid code. At some place the variable name is written without safe-guarding it with a call to [`normalize_identifier()`](https://github.com/rinja-rs/rinja/blob/b856eb8d44b9021fcd7ab123bcf8e5d1ef0d0f3a/rinja_derive/src/generator.rs#L2974-L2998). Most likely inside [`visit_call()`](https://github.com/rinja-rs/rinja/blob/b856eb8d44b9021fcd7ab123bcf8e5d1ef0d0f3a/rinja_derive/src/generator.rs#L1994-L2051).

Maybe you would like to investigate further and provide a bug fix, @chrisp60?

**Comment by chrisp60** [comment]
That sounds straightforward. I will take a look and submit a PR (as time allows). Thanks for the hints on where to start.
