### ISSUE TITLE
Option to minify rendered html

### ISSUE THREAD

**Issue by bshankar** [rinja-rs/rinja#281]
Would it be possible to add an option to minify HTML output so that it will be in a single line without any whitespaces between tags?

I need this functionality because there's a potential conflict with [Datastar](https://github.com/delaneyj/datastar). It sends HTML in SSE events and SSE uses newlines as delimiters for each command.

```
event: datastar-merge-fragments
data: fragments <div id="login-error" class="alert alert-error"> ... </div>
...
```

**Comment by GuillaumeGomez** [comment]
Minifying HTML is more complex than it might sound. I recommend would to write your own filter (if applied directly inside the HTML templates) or your own function when the HTML has been rendered.

From a quick search, there seems to be [minify-html](https://crates.io/crates/minify-html) doing that.

**Comment by bshankar** [comment]
Thank you for the tip @GuillaumeGomez! I will use minify-html after HTML has been rendered. Closing.
