### ISSUE TITLE
Rinja book references `main` branch, but `master` is used.

### ISSUE THREAD

**Issue by FalkWoldmann** [rinja-rs/rinja#33]
For instance, the link to `axum` example on https://rinja.readthedocs.io/en/latest/integrations.html leads to https://github.com/rinja-rs/rinja/blob/main/rinja_axum/tests/basic.rs, which does not exist, since the main branch is called master (https://github.com/rinja-rs/rinja/blob/master/rinja_axum/tests/basic.rs).

**Comment by GuillaumeGomez** [comment]
Oh indeed, thanks!
