### ISSUE TITLE
Don't generate part of templates if we "know" (ie, we have literal's value) that it will never be entered

### ISSUE THREAD

**Issue by GuillaumeGomez** [rinja-rs/rinja#47]
For example:

```jinja
{% set x = true %}

{% if x %}
bla
{% else %}
blo
{% endif %}
```

In this case, we know for absolutely sure that it'll never enter the `else` block, so we could completely remove the condition.

Same could be done with other literals (like string).

**Comment by Kijewski** [comment]
Is this actually needed? LLVM will eliminate such sections at any optimization level but `-O0`.

**Comment by GuillaumeGomez** [comment]
It's not about runtime perf but compilation perf: if you remove some parts of the template, you generate less code (so faster IO) which means you have less code to parse and compile (compile-time perf).

**Comment by GuillaumeGomez** [comment]
Now that #62 has been merged, I will give a try to this one. ie, if a literal in a template is stored in a template variable and then used in a comparison. Sounds like fun. :D

**Comment by Kijewski** [comment]
Yes, I think we can let rustc + llvm do the heavy lifting. They will do an analysis anyway, and can look beyond our limited view inside a proc-macro.

**Comment by GuillaumeGomez** [comment]
Closing then!
