### ISSUE TITLE
`|linebreaks`, `|linebreaksbr` and `|paragraphbreaks` don't work as intended with regards to escaping

### ISSUE THREAD

**Issue by Kijewski** [rinja-rs/rinja#74]
The examples in the book to e.g. `|paragraphbreaks` are wrong. The output of

```jinja2
{{ "hello\n\nworld"|paragraphbreaks }}
```

isn't 

```html
<p>hello</p><p>world</p>
```

but

```html
&#60;p&#62;hello&#60;/p&#62;&#60;p&#62;world&#60;/p&#62;
```

because the filter is not marked as HTML safe, i.e. it returns `Result<impl fmt::Display, Infallible>` instead of `Result<HtmlSafeOutput<impl fmt::Display>, Infallible>`. That makes it tempting to use `{{ "hello\n\nworld"|paragraphbreaks|safe }}`, but the output of `|paragraphbreaks` is not safe, because it does not escape its input.

Should we auto-escape the input of `|paragraphbreaks` and mark its output as safe? Right now you can do that manually with `{{ "hello\n\nworld"|escape|paragraphbreaks|safe }}`, which looks ridiculous.

**Comment by GuillaumeGomez** [comment]
Yes sounds like a good idea!
