### ISSUE TITLE
First release?

### ISSUE THREAD

**Issue by GuillaumeGomez** [rinja-rs/rinja#79]
Everything is ready for docs.rs, just need to make a release. The new changes I wrote can be part of the next release, so not really urgent.

Do you have anything in mind you want to be merged before we make this release @Kijewski ?

**Comment by Kijewski** [comment]
I'd only add #80 before the release:

- #80

Then I think we are ready! The other open PRs can be added later.

**Comment by GuillaumeGomez** [comment]
Perfect, gonna release them and then provide co-ownership to you.

**Comment by GuillaumeGomez** [comment]
All released. I'll let you close this issue once you have accepted all the invites.

**Comment by GuillaumeGomez** [comment]
Hum also, maybe we should have a `0.2` publication of the book too?

**Comment by Kijewski** [comment]
It will be added when you push the tag to github.

**Comment by GuillaumeGomez** [comment]
Damn, you're good at this! :open_mouth:

**Comment by Kijewski** [comment]
Half of my releases get a post-release because I'm not. :D

Let's see if there are bugs that only show up in production, or if we got it right on the first attempt. :D Anyways, nice to work with you. I think I can say "well done!" to the both of us. :)

**Comment by GuillaumeGomez** [comment]
> Half of my releases get a post-release because I'm not. :D

Welcome to the club! :laughing: 

Just one question: what form does the tag needs to be before I push it?

**Comment by Kijewski** [comment]
I like it better with a prefixed "v". I don't think rtd would mind either way, but I only ever used it with the prefix.

**Comment by GuillaumeGomez** [comment]
Ok docs are all good. Gonna write a blog post about `rinja` then to share on socials etc. Like written above, I'll let you close once you have accepted all invites on crates.io.

**Comment by Kijewski** [comment]
I accepted the invites. I'm curious to read the blog post. :)

**Comment by GuillaumeGomez** [comment]
I'll send the link to you by email before making it public then.
