### ISSUE TITLE
Allow blocks within control structures

### ISSUE THREAD

**Issue by vanhouc** [rinja-rs/rinja#81]
I've been using Askamas main branch (now rinja) to template out an HTMX based application using the new template block partial feature. However the fact that blocks can only be declared at the top level means that it heavily restricts being able to send fragments within for loops or if branches. This means that I'm restricted to only the highest level elements to send as block partials.

I have a small amount of experience working on parsers so if one of the maintainers is willing to chime in on the feasibility of this I would be happy to take a shot at a PR.

**Comment by GuillaumeGomez** [comment]
Just to be sure, a block `{% block block_name %}` can only update the content where it was originally declared. So in the case of loops, it means we'd need to know ahead of time what variable would be available. As such, I'm not sure to see how it can done.

Why wouldn't template macros or `include` not fit in your case?

**Comment by vanhouc** [comment]
You're right macros and include do work. The ergonomics of blocks are just very nice for HTMX as it allows easily marking portions of the tree as independently renderable without moving the content out of tree into a macro or into a separate included template since these fragments are only ever referenced by the original template.

I see your point now about how it would be impossible to render the block if it needed context about control flow from the full template.

**Comment by GuillaumeGomez** [comment]
With rinja at least it's not possible. For other jinja template engines, I don't see issues doing that.
