### ISSUE TITLE
book: section "Template Expansion" is quite outdated by now

### ISSUE THREAD

**Issue by Kijewski** [rinja-rs/rinja#94]
<https://rinja.readthedocs.io/en/v0.2.0/template_expansion.html>

Do we need this section, though? Askama aims to generate readable code, code that is similar to what a programmer would write when translating a template by hand. Rinja generates obscenely unreadable code that is hopefully in many cases somewhat better than (at least a naive) implementation by hand, or at least that is my goal. :)

Maybe we should pull the page from the index for now?

**Comment by GuillaumeGomez** [comment]
Hum... I think it doesn't make much sense to keep it indeed. Sending a PR to remove it.
